# Generated by Django 4.0.5 on 2022-06-10 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=10, verbose_name='Name der Kategorie')),
            ],
            options={
                'verbose_name': 'Kategorie',
                'verbose_name_plural': 'Kategorien',
            },
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'verbose_name': 'Raum', 'verbose_name_plural': 'Räume'},
        ),
        migrations.CreateModel(
            name='DeviceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=10, verbose_name='Marke')),
                ('model', models.CharField(max_length=10, verbose_name='Geräte Modell')),
                ('category', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory_management.devicecategory', verbose_name='Kategorie')),
            ],
            options={
                'verbose_name': 'Geräte Typ',
                'verbose_name_plural': 'Geräte Typen',
            },
        ),
    ]
