# Generated by Django 4.0.5 on 2022-06-10 13:45

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0002_devicecategory_alter_room_options_devicetype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_num', models.CharField(default=None, max_length=20, verbose_name='Serien Nummer')),
                ('production_date', models.DateField(default=datetime.date.today, verbose_name='Produktion Datum')),
                ('waranty_date', models.DateField(default=datetime.date.today, verbose_name='Garanti Datum')),
                ('device_type', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory_management.devicetype', verbose_name='Kategorie')),
            ],
            options={
                'verbose_name': 'Geräte',
                'verbose_name_plural': 'Geräte',
            },
        ),
    ]
