# Generated by Django 4.0.5 on 2022-06-10 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0004_remove_device_waranty_date_device_warranty_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='devices',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory_management.device'),
        ),
    ]
