# Generated by Django 4.0.5 on 2022-06-10 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0007_location_device_issues_otherequipment_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='otherequipment',
            options={'verbose_name': 'Sonstige Ausstatung', 'verbose_name_plural': 'Sonstige Ausstatungen'},
        ),
        migrations.AddField(
            model_name='device',
            name='hints',
            field=models.CharField(blank=True, default='keine Hinweise', max_length=50, verbose_name='Hinweise'),
        ),
        migrations.AlterField(
            model_name='location',
            name='building',
            field=models.CharField(choices=[('BA1', 'Bauabschnitt 1'), ('BA2', 'Bauabschnitt 2')], default='Bauabschnitt 1', max_length=10, verbose_name='Bauabschnitt'),
        ),
        migrations.AlterField(
            model_name='location',
            name='floor',
            field=models.CharField(choices=[('UG', 'Untergeschoos'), ('EG', 'Edgesschoss'), ('1F', 'Erster Stock'), ('2F', 'Zweiter Stock')], default='1F', max_length=10, verbose_name='Stockwerk'),
        ),
    ]
