# Generated by Django 4.0.5 on 2022-06-11 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0008_alter_otherequipment_options_device_hints_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='floor',
            field=models.CharField(choices=[('UG', 'Untergeschoos'), ('EG', 'Edgesschoss'), ('1S', 'Erster Stock'), ('2S', 'Zweiter Stock')], default='1F', max_length=10, verbose_name='Stockwerk'),
        ),
    ]
