# Generated by Django 4.0.5 on 2022-06-12 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0010_device_is_working'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='is_working',
            field=models.CharField(choices=[('0', 'Gerät Funktioniert'), ('1', 'Gerät Funktioniert NICHT')], default='Gerät Funktioniert', max_length=13, verbose_name='Funktonsfähig?'),
        ),
    ]
